src/macros.rs
src/search/aggregations/bucket/mod.rs
src/search/aggregations/bucket/terms_aggregation.rs
src/search/aggregations/metrics/mod.rs
src/search/aggregations/mod.rs
src/search/aggregations/pipeline/mod.rs

Aggregations will be structured identically as queries for a more consistent API.

Refactor aggregations to have identical structure to queries

---

README.md
examples/boolean-query/src/main.rs
examples/simple-query/src/main.rs
src/search/request.rs

This makes API neater to use, users won't have to explicitly suffix numbers with u64 suffix. It will ignore negative values.

Use TryInto for from/size values

---

src/lib.rs

```#![doc = include_str!("../README.md")]``` is still relatively new and does not compile on pre 1.54.0 versions

Hardcode docs for compatibility

---

src/search/queries/geo/geo_bounding_box_query.rs

This occurred due to changes in https://github.com/vinted/elasticsearch-dsl-rs/pull/40

Fix geo bounding box query test

---

Cargo.toml

Crate requires serialization only.

Disable default Chrono features

---

Cargo.toml
src/search/queries/geo/geo_bounding_box_query.rs
src/search/queries/geo/geo_distance_query.rs
src/search/queries/mod.rs

This should allow us to use Geo queries with actual query DSL :smile: 
Ref https://github.com/vinted/elasticsearch-dsl-rs/pull/41, https://github.com/vinted/elasticsearch-dsl-rs/pull/49.
Example error:
```
69 | ...                   .should(
|                        ^^^^^^ the trait `From<GeoDistanceQuery>` is not implemented for `std::option::Option<elasticsearch_dsl::Query>`
```

Add missing geo query conversions to Query

---

src/search/response.rs

Adding one extra field, that is in the hit hash.
@buinauskas @vinted/boost

Adding 'fields' field to elasticsearch response

---

Cargo.toml
src/search/queries/custom/json_query.rs
src/search/queries/custom/mod.rs
src/search/queries/mod.rs

Allow passing a raw JSON query, this might be useful for scaffolding, not-yet-supported queries or queries provided by plugins.

Implement raw JSON query

---

Cargo.toml
src/search/aggregations/metrics/avg_aggregation.rs
src/search/aggregations/metrics/boxplot_aggregation.rs
src/search/aggregations/metrics/max_aggregation.rs
src/search/aggregations/metrics/min_aggregation.rs
src/search/aggregations/metrics/sum_aggregation.rs
src/search/params/mod.rs
src/search/params/number.rs

This is more English than `Numeric`.

Rename `Numeric` to `Number`

---

Cargo.toml
src/search/response.rs

Hit can be considered equal to another hit when index and id are equal.

Implement Hit PartialEq manually

---

src/search/params/mod.rs
src/search/params/text.rs

Instead of using raw `String`, this introduces a `Text` type (ES convention as well) with conversions from strings and optional strings. Later I'll introduce this in text queries.

Introduce text type

---

Cargo.toml
src/search/response.rs

Reverts vinted/elasticsearch-dsl-rs#60
It's better to leave structural equality and let one override if it needed with a newtype

Revert "Implement Hit PartialEq manually"

---

src/search/params/term.rs

To avoid logic duplication, Term enum will now use Number to represent a single number instead of multiple variants that Number now implements.

Reuse Number in Term

---

src/macros.rs

This works better in IDEs and with rust-analyzer when generic names are explicit.

Use explicit generic types in macros

---

src/search/sort/mod.rs

- Allow specifying custom Term value instead of a String
- Accept anything that implements ToString for a custom SortField

Improve sorting API friendliness

---

src/search/params/date.rs
src/search/params/number.rs
src/search/params/term.rs

Custom order and ordering implementations were done for number variant only, they are now handled in Number struct.

Cleanup date, number, term

---

src/search/queries/compound/dis_max_query.rs
src/search/queries/full_text/multi_match_query.rs
src/search/queries/params/tie_breaker.rs

It was incorrect to use from implementation and cap the result. This will use try from instead.

Fix TieBreaker implementation

---

examples/aggregations/Cargo.toml
examples/aggregations/src/main.rs
src/macros.rs
src/search/aggregations/bucket/terms_aggregation.rs
src/search/aggregations/metrics/avg_aggregation.rs
src/search/aggregations/metrics/boxplot_aggregation.rs
src/search/aggregations/metrics/cardinality_aggregation.rs
src/search/aggregations/metrics/max_aggregation.rs
src/search/aggregations/metrics/min_aggregation.rs
src/search/aggregations/metrics/rate_aggregation.rs
src/search/aggregations/metrics/sum_aggregation.rs
src/search/aggregations/metrics/top_hits_aggregation.rs
src/search/aggregations/mod.rs
src/search/aggregations/params/aggregation_name.rs
src/search/aggregations/params/mod.rs
src/search/request.rs

This is a breaking change that removes `name` from the aggregation itself and moves it onto `.aggregate(aggregation_name, aggregation)` method where it actually always belonged, this makes API more consistent, clearer. It also adds a AggregationName newtype.

Refactor aggregations builder

---

src/search/params/geo_shapes.rs
src/search/queries/geo/geo_shape_query.rs
src/search/queries/geo/mod.rs
src/search/queries/mod.rs

First query iteration, GeoShape enum needs more love for a better API.

Implement geo_shape query

---

Cargo.toml
README.md
src/lib.rs

Query DSL is almost complete, only span queries remain, it's fine to bump the minor version and release 0.2.00

Bump version to 0.2.0

---

Cargo.toml
src/search/highlight/mod.rs

This will serialize more consistently as well as provide consistent order for highlighting.

Use explicit order in highlighter

---

Cargo.toml
src/search/request.rs

These are rarer, but still useful options for advanced use cases.

Implement indices boost and min score

---

src/search/aggregations/bucket/terms_aggregation.rs

Add 'missing' field to terms aggregation

---

Cargo.toml
src/search/queries/params/percolate_query.rs
src/search/queries/specialized/percolate_query.rs

This should simplify DSL and would not require creating Value manually.
cc @vinted/boost

Allow passing any structure to percolator query

---

src/search/highlight/mod.rs
src/search/highlight/order.rs

When using highlight's `order(Order)`, the output json gives `null` no matter what order is actually set.
Try to fix this by removing the `untagged` from `Order`.

fix highlight order null serde

---

src/search/aggregations/bucket/filter_aggregation.rs

Missed accidentally, this is unused.

Remove unused internal code

---

Cargo.toml
src/search/aggregations/mod.rs

Probably was missing in yesterdays commit.
@buinauskas

fix: add filter agg to aggregation macro

---

src/search/queries/mod.rs

It's more efficient to match than to clone a query just for comparison.

Remove cloning from Query PartialEq impl

---

Cargo.toml
src/search/params/date.rs
src/search/params/number.rs
src/search/params/term.rs
src/search/params/terms.rs
src/search/params/text.rs
src/search/queries/params/boost.rs
src/search/queries/params/negative_boost.rs
src/util/key_value_pair.rs

Debug implementations have become nightmare to read, reimplement some of them manually for better readability.

Overwrite debug implementations for leaf structs

---

Cargo.toml
src/search/response.rs

Elasticsearch can return multiple keyed inner hits, not just one under the `items` key.
This changes inner hits from Option[InnerHit] to a map of key/inner_hit pairs and defers value deserialization by using serde_json's RawValue. They will be deserialized on demand.

Allow handling multiple inner hits

---

Cargo.toml
src/search/response.rs

Reverts vinted/elasticsearch-dsl-rs#143
Will handle this in a larger PR covering the whole _source field.

Revert "Allow handling multiple inner hits"

---

Cargo.toml
src/search/response.rs

There are several problems that this change fixes/adjusts:
- reduced required typing, currently type for hit/inner hit always had to be specified
- switch to deferred source structure allows to skip expensive deserialization/serialization, this helps for large documents that only need to be transferred over the wire, if one wants to deserialize data, this can be done using the `.source()` method on the hit
- inner hits were incorrectly modeled, there can be many inner hits and `items` was something we've used in our domain that was carried over, inner hits are a map of key/value pairs, where the key is the hit name, and value is the inner hit
cc @ernestas-vinted  @vinted/boost please review this

Defer document source deserialization

---

src/search/queries/compound/function_score_query.rs
src/search/response.rs

As per docs, nested hits can be deeply nested https://www.elastic.co/guide/en/elasticsearch/reference/current/inner-hits.html#hierarchical-nested-inner-hits.
Reflect this in search response.

Allow deeply nested Nested structures

---

src/search/highlight/matched_fields.rs

This will render cleaner debug strings.

Reuse matched fields debug syntax

---

src/util/should_skip.rs

Replace fully qualified imports, remove redundant lifetimes.

Simplify ShouldSkip implementations

---

src/search/highlight/encoder.rs
src/search/highlight/fragmenter.rs
src/search/highlight/order.rs
src/search/params/units.rs
src/search/queries/params/function_score_query.rs
src/search/queries/params/has_child_query.rs
src/search/queries/params/zero_terms_query.rs

snake case will cover lowercase variant too and will be more consistent within the project.

Use consistent rename_all

---

src/search/queries/compound/function_score_query.rs
src/search/queries/params/function_score_query.rs

This aligns better with the official naming.

Rename FunctionScoreBoostMode to FunctionBoostMode

---

src/search/highlight/encoder.rs
src/search/highlight/fragmenter.rs

Using untagged macro attribute will screw enums serialization up - removing it.

Fix enums with incorrectly used untagged variant.

---

src/search/queries/specialized/percolate_lookup_query.rs
src/search/request.rs

There's no point to have TryInto for u64 operators, use simpler types.

Remove redundant TryInto operators

---

src/macros.rs
src/search/queries/geo/geo_bounding_box_query.rs
src/search/queries/geo/geo_distance_query.rs
src/search/queries/geo/geo_shape_lookup_query.rs
src/search/queries/geo/geo_shape_query.rs
src/search/queries/shape/shape_lookup_query.rs
src/search/queries/shape/shape_query.rs
src/search/queries/term_level/terms_lookup_query.rs
src/search/queries/term_level/terms_query.rs

Getting rid of KeyValuePair helper from the query structures. It is fine for serialization, but should not be used in the actual structures. I'll remove it from the other structures as well, the intention is to only use it in serialization helpers.

Add serialization wrapper for other container queries

---

src/lib.rs
src/search/aggregations/mod.rs
src/search/queries/params/pinned_query.rs
src/search/queries/params/script_object.rs
src/search/queries/specialized/more_like_this_query.rs
src/search/queries/term_level/ids_query.rs
src/search/request.rs
src/search/response/error_cause.rs
src/search/response/hit.rs
src/search/response/search_response.rs
src/search/response/suggest_option.rs
src/search/suggesters/completion_suggester.rs
src/types.rs
src/util/should_skip.rs

There was a mix of hashmaps and btreemaps in the lib, adding Set/Map alias for consistent and simplified usage.

Use consistent Map, Set types

---

src/search/rescoring/rescore_.rs

So that values can be set as 1, 0.

Cast rescore query weights to float

---

Cargo.toml

A large release with lots of cleanup:
- Relaxed query construction, terms queries now accept anything that's serializable, this won't require creating custom From<T> For Term conversions
- Support for all types of sorting criteria
- Support for completions
- Improved search responses with delayed parsing
- Correct inner hits support
- And much more.

Bump to 0.4

---

.github/workflows/CI.yml
src/search/response/search_response.rs

This switches to nextest runner and will run ci build in a single workflow instead of multiple parallel ones, this will be cheaper.

Improve CI builds

---

src/search/aggregations/bucket/diversified_sampler_aggregation.rs

I swapped the comments for two variants to correctly match the official Elasticsearch documentation.
See latest documentation for [execution_hint in diversified sampler aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-diversified-sampler-aggregation.html#_execution_hint).

Update docs for ExecutionHint enum

---

Cargo.toml
src/lib.rs
src/search/queries/params/mod.rs
src/search/queries/params/stored_fields.rs
src/search/queries/specialized/more_like_this_query.rs
src/search/request.rs

One of the upgrades broker Elasticsearch internals, which no longer accept `["_none_"]` as a valid docvalue field, it explicitly expects `"_none_"` - a single string value.
Handle this by introducing a `StoredFields` enum which will contain the exact None case and regular fields. This should be a non-breaking change because a collection of single _none_ item will be serialized as _none_ string.

Fix stored fields _none_ case

---

src/search/request.rs
src/util/assert_serialize.rs

Post filter is a regular query executed after aggregation phase. Solves https://github.com/vinted/elasticsearch-dsl-rs/issues/218.

Implement post filter

---

Cargo.toml

Releases https://github.com/vinted/elasticsearch-dsl-rs/issues/217, https://github.com/vinted/elasticsearch-dsl-rs/issues/218

Bump version to 0.4.14

---

src/search/response/search_response.rs

The scroll id is returned as `_scroll_id` in the elasticsearch JSON payload.
See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-api-response-body

Renaming scroll_id to _scroll_id.

---

Cargo.toml

Releases https://github.com/vinted/elasticsearch-dsl-rs/pull/222.

Bump version to 0.4.15

---

src/search/params/terms.rs
src/search/request.rs

Hi, thanks for maintaining this great library!
https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after

Add support for `search_after` request API

---

Cargo.toml

Releases https://github.com/vinted/elasticsearch-dsl-rs/pull/226.

Bump version to 0.4.16

---

src/search/queries/span/span_near_query.rs

Addresses https://github.com/vinted/elasticsearch-dsl-rs/issues/228, there are official docs for `in_order` param, so I had to improvize.

Fix span near query todo comments

---

src/search/aggregations/metrics/max_aggregation.rs
src/search/aggregations/metrics/min_aggregation.rs
src/search/aggregations/metrics/sum_aggregation.rs

This allows to use script instead of field for min, max and sum aggs.
Example:
```javascript
aggs: {
"max_score" : {
"max": {
"script": {
"source": "_score"
}
}
},
"sum_score" : {
"sum": {
"script": {
"source": "_score"
}
}
}
}
```

Add support for script in min, max and sum aggregations

---

src/search/queries/joining/has_child_query.rs

Closes https://github.com/vinted/elasticsearch-dsl-rs/issues/236.

Implement inner hits for has child query

---

.github/workflows/CI.yml

The action is redundant as well as llvm-tools-preview component.

Remove codecov installation action

---

src/search/request.rs

Adding a `timeout` parameter for search queries.
more details: https://www.elastic.co/guide/en/elasticsearch/reference/8.9/search-your-data.html#search-timeout

Add timeout param

---

src/search/queries/params/function_score_query.rs

Looks like f32 and f64 were missed from the `Function` macro defined [here](https://github.com/vinted/elasticsearch-dsl-rs/blob/master/src/search/queries/params/function_score_query.rs#L97-L112)
This pr adds the missing float types to the list and adds a test to ensure it is serialised correctly
docs: [function score query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#:~:text=must%20be%20a-,numeric,-%2C%20date%2C%20or%20geopoint) supports all [numeric field types](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html)

Support f32 and f64 in decay functions

---

src/search/queries/specialized/distance_feature_query.rs
src/search/request.rs

Hello! Thanks for this crate!
What do you think about adding a catch-all field for unimplemented fields? Today I needed [`knn`](https://www.elastic.co/guide/en/elasticsearch/reference/8.13/search-search.html#search-api-knn)  but it was missing. 
So I took an approach similar to [`Query::json()`](https://github.com/vinted/elasticsearch-dsl-rs/blob/master/src/search/queries/custom/json_query.rs#L4) but for top-level `struct Search`.

Add support for custom fields

---

src/search/knn/mod.rs
src/search/mod.rs
src/search/queries/mod.rs
src/search/queries/specialized/knn_query.rs
src/search/queries/specialized/mod.rs
src/search/request.rs

Addresses the missing kNN support coming from https://github.com/vinted/elasticsearch-dsl-rs/pull/265.
There are two ways to query nearest vectors in elasticsearch:
- top-level kNN search object
- kNN query
They are slightly similar but different at the time, kNN query is considered expert mode, has fewer fields so I kept these objects separate for type-safety. 
@DmitrySamoylov do you mind double checking if this is as expected? I went through the documentation and seems like I've covered everything.

feat: add kNN search, query support

---

src/search/aggregations/bucket/terms_aggregation.rs
src/search/aggregations/params/mod.rs
src/search/aggregations/params/terms_exclude.rs
src/search/aggregations/params/terms_include.rs

https://github.com/vinted/elasticsearch-dsl-rs/pull/254 is inactive, implements include/exclude for terms aggregations as per spec.

feat: add terms aggregation include, exclude

---

src/search/aggregations/bucket/geotile_grid_aggregation.rs
src/search/aggregations/bucket/mod.rs
src/search/aggregations/mod.rs

Try to implement [geotile grid aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geotilegrid-aggregation.html)

Implement geotile grid aggregation

---

.github/dependabot.yml

I would like to avoid updating serde and serde_json in separate pull requests, let's ask dependabot to group them.

dependabot: update serde dependencies in group

---

src/search/sort/field_sort.rs
src/search/sort/mod.rs
src/search/sort/nested_field_sort.rs

Adds support for sorting within nested objects, as per:
https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html#nested-sorting
The syntax looks like this:
```rust
Sort::FieldSort(
FieldSort::descending("applications.date").nested(NestedFieldSort::path("applications")),
)
```
Further examples can be found in the tests within the commit. Please let me know if you are unhappy with the API/syntax and I'm happy to make changes. Thank you!

Implement sorting within nested objects
