vinted/elasticsearch-dsl-rs

- src/search/aggregations/bucket/terms_aggregation.rs
- src/search/aggregations/metrics/top_hits_aggregation.rs
- src/search/queries/compound/bool_query.rs
- src/search/queries/compound/boosting_query.rs
- src/search/queries/compound/constant_score_query.rs
- src/search/queries/compound/dis_max_query.rs
- src/search/queries/compound/function_score_query.rs
- src/search/queries/full_text/match_bool_prefix_query.rs
- src/search/queries/full_text/match_phrase_prefix_query.rs
- src/search/queries/full_text/match_phrase_query.rs
- src/search/queries/full_text/match_query.rs
- src/search/queries/full_text/multi_match_query.rs
- src/search/queries/joining/nested_query.rs
- src/search/queries/match_all_query.rs
- src/search/queries/match_none_query.rs
- src/search/queries/specialized/distance_feature_query.rs
- src/search/queries/specialized/more_like_this_query.rs
- src/search/queries/specialized/percolate_query.rs
- src/search/queries/specialized/rank_feature_query.rs
- src/search/queries/term_level/exists_query.rs
- src/search/queries/term_level/fuzzy_query.rs
- src/search/queries/term_level/ids_query.rs
- src/search/queries/term_level/prefix_query.rs
- src/search/queries/term_level/range_query.rs
- src/search/queries/term_level/regexp_query.rs
- src/search/queries/term_level/term_query.rs
- src/search/queries/term_level/terms_query.rs
- src/search/queries/term_level/terms_set_query.rs
- src/search/queries/term_level/wildcard_query.rs
Removes duplicate query/aggregation constructs.
> Refactor queries/aggregations constructs

- src/search/aggregations/bucket/terms_aggregation.rs
Make use of KeyValur pair instead of implementing serialization manually.
> Refactor TermsAggregationOrder serialization

- src/search/queries/geo/geo_distance_query.rs
- src/search/queries/geo/mod.rs
- src/search/queries/params/geo_query.rs
Documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-query.html
Used https://github.com/vinted/elasticsearch-dsl-rs/pull/41 as reference.
> Implement GeoDistance query

- Cargo.toml
- src/search/queries/params/boost.rs
> Fix  boost to boost comparison

- src/search/aggregations/bucket/terms_aggregation.rs
- src/search/aggregations/metrics/top_hits_aggregation.rs
- src/search/queries/params/inner_hits.rs
- src/search/rescoring/mod.rs
> Use TryFrom for from/size arguments

- src/search/params/number.rs
> Implement Display for Number

- src/search/params/text.rs
- src/search/queries/full_text/combined_fields_query.rs
- src/search/queries/full_text/match_bool_prefix_query.rs
- src/search/queries/full_text/match_phrase_prefix_query.rs
- src/search/queries/full_text/match_phrase_query.rs
- src/search/queries/full_text/match_query.rs
- src/search/queries/full_text/multi_match_query.rs
- src/search/queries/full_text/query_string_query.rs
- src/search/queries/full_text/simple_query_string_query.rs
This will allow handling optional search queries easier.
> Replace String with Text for FTS queries

- src/search/params/number.rs
Restructures the number struct for reusability, changes U64 from I64 to positive and negative variants for easier comparison.
> Wrap Number in an internal enum

- examples/domain-specific-dsl/Cargo.toml
- examples/domain-specific-dsl/src/main.rs
An example showing how to possibly build a custom DSL for domain specific queries.
> Add domain-specific DSL example

- examples/domain-specific-dsl/src/main.rs
- src/search/params/number.rs
- src/search/params/term.rs
This also updates custom domain dsl example.
> Allow converting number reference into Number/Term structures

- src/analyze/request.rs
- src/analyze/response.rs
- No longer uses a mix of implicit and explicit generic parameters
- Simplifies analyze response deserialization
> Make analyze api more consistent

- src/search/queries/compound/bool_query.rs
- src/search/queries/compound/dis_max_query.rs
- src/search/queries/mod.rs
Removes duplicate logic from bool/dis_max queries
> Deduplicate multiple queries addition

- Cargo.toml
- src/search/params/date.rs
- src/search/params/mod.rs
- src/search/params/term.rs
Do not enforce chrono use - allow SystemTime as well.
> Allow SystemTime for Date term

- src/search/params/search.rs
Refactor to increase code readability and consistency.
> Improve search params conversions

- src/search/queries/params/geo_query.rs
Make formatting consistent with rest of the project.
> Reformat geo_boundinx_box query code

- src/search/queries/geo/geo_shape_lookup_query.rs
- src/search/queries/geo/mod.rs
- src/search/queries/mod.rs
Part of https://github.com/vinted/elasticsearch-dsl-rs/issues/32
> Implement geo shape lookup query

- src/search/queries/mod.rs
- src/search/queries/specialized/mod.rs
- src/search/queries/specialized/wrapper_query.rs
> Implement wrapper query

- src/search/mod.rs
- src/search/queries/params/mod.rs
- src/search/queries/params/script_object.rs
Do not allow both id and source to be specified
> Fix script object

- src/search/highlight/matched_fields.rs
- src/search/queries/compound/bool_query.rs
- src/search/queries/params/minimum_should_match.rs
- src/search/queries/params/mod.rs
Cleanup types and make them more generic and more convertible.
> Cleanup newtypes

- examples/boolean-query/src/main.rs
- src/search/queries/compound/bool_query.rs
- src/search/queries/compound/dis_max_query.rs
- src/search/queries/mod.rs
This removes duplicate methods for a single and multiple queries addition and makes DSL more streamlined.
> Streamline compound queries composition

- README.md
- src/lib.rs
Adds a larger example with aggregations in README file as well as docs.rs README.
> Update README with aggregations

- src/search/params/geo_coordinate.rs
- src/search/params/geo_shapes.rs
- src/search/params/mod.rs
Implement geo shapes for further geo shape queries.
> Draft geo shapes structures

- src/search/params/coordinate.rs
- src/search/params/geo_coordinate.rs
Might be useful for API consumers.
> Implement FromStr for coordinate types

- src/search/params/geo_shape.rs
Envelope consists of two points only: top left and bottom right.
> Simplify envelope construction

- src/search/params/geo_shape.rs
- src/search/params/shape.rs
Clearer and will be serialized the same way.
> Convert envelope coordinates to tuple

- src/search/queries/mod.rs
- src/search/queries/shape/mod.rs
- src/search/queries/shape/shape_lookup_query.rs
- src/search/queries/shape/shape_query.rs
Implements shape queries as well as fixes some inconsistencies found in geo shape queries.
> Implement shape queries

- Cargo.toml
Breaking changes:
- https://github.com/vinted/elasticsearch-dsl-rs/pull/93
> Release 0.1.12

- Cargo.toml
- src/search/queries/mod.rs
Didn't allow adding queries converted into an Query enum.
> Impl IntoIterator for Query enum

- src/search/queries/mod.rs
This has been really untested, good starting point.
> Test query addition

- src/search/queries/mod.rs
- src/search/queries/params/script_object.rs
- src/search/queries/specialized/mod.rs
- src/search/queries/specialized/script_query.rs
- src/search/queries/specialized/script_score_query.rs
These were the only missing specialized queries.
> Add script and script score queries

- Cargo.toml
- src/search/mod.rs
- src/search/request.rs
- src/search/runtime_mappings/mod.rs
Recent ES feature allowing to define runtime mappings at search time.
> Implement runtime mappings

- .github/workflows/update-contributors.yml
This action will automatically update contributors file once a month.
> Update contributors once a month

- src/search/runtime_mappings/mod.rs
These were all pointing to incorrect structures.
> Fix RuntimeMapping docs

- src/search/aggregations/bucket/diversified_sampler_aggregation.rs
- src/search/aggregations/bucket/mod.rs
- src/search/aggregations/bucket/sampler_aggregation.rs
- src/search/aggregations/mod.rs
> Diversified sampler aggregation

- Cargo.toml
- src/search/queries/mod.rs
> Implement PartialEq for query variants

- src/search/aggregations/mod.rs
- src/search/aggregations/params/aggregation_name.rs
- src/search/queries/mod.rs
> Simplify query, aggregation debug views

- Cargo.toml
- src/search/params/search_filter.rs
This will cover more types and make public API more convenient.
> Make source filter From conversions more generic

- src/search/aggregations/bucket/diversified_sampler_aggregation.rs
- src/search/aggregations/bucket/filter_aggregation.rs
- src/search/aggregations/bucket/sampler_aggregation.rs
- src/search/aggregations/bucket/terms_aggregation.rs
- src/search/aggregations/metrics/avg_aggregation.rs
- src/search/aggregations/metrics/boxplot_aggregation.rs
- src/search/aggregations/metrics/cardinality_aggregation.rs
- src/search/aggregations/metrics/max_aggregation.rs
- src/search/aggregations/metrics/min_aggregation.rs
- src/search/aggregations/metrics/rate_aggregation.rs
- src/search/aggregations/metrics/sum_aggregation.rs
- src/search/aggregations/metrics/top_hits_aggregation.rs
- src/search/aggregations/mod.rs
- src/util/assert_serialize.rs
Checks serialization as well as it was added to the `Aggregation` enum.
> Add dedicated aggregations serialization tester

- src/util/key_value_pair.rs
This will render nicer and more consistent debug views.
> Improve KeyValuePair debug implementation

- src/search/aggregations/bucket/terms_aggregation.rs
- src/search/params/term.rs
- src/search/params/terms.rs
- src/search/queries/params/function_score_query.rs
- src/search/queries/term_level/fuzzy_query.rs
- src/search/queries/term_level/prefix_query.rs
- src/search/queries/term_level/range_query.rs
- src/search/queries/term_level/term_query.rs
- src/search/queries/term_level/wildcard_query.rs
- src/search/sort/mod.rs
> Tweak term serialization

- src/search/aggregations/bucket/terms_aggregation.rs
- src/search/aggregations/params/mod.rs
- src/search/aggregations/params/terms_order.rs
This will provide a more concise query writing experience.
> Improve terms aggregation ordering

- src/search/sort/mod.rs
- src/search/sort/sort_field.rs
- src/search/sort/sort_missing.rs
- src/search/sort/sort_mode.rs
- src/search/sort/sort_order.rs
File became too large, reorganize into smaller ones.
> Reorganize sort module

- src/search/queries/compound/bool_query.rs
- src/search/queries/compound/dis_max_query.rs
- src/search/queries/mod.rs
Will match `SortCollection` naming.
> Rename Queries to QueryCollection

- src/macros.rs
- src/search/sort/mod.rs
This will not require to introduce inner structures just to satisfy the serialization.
> Introduce keyed sorting for complex structures

- src/util/key_value_pair.rs
This will yield clearer debug messages.
> Improve key value pair debug logic

- src/search/params/geo_distance_type.rs
- src/search/params/geo_point.rs
- src/search/params/mod.rs
- src/search/params/units.rs
- src/search/sort/geo_distance_sort.rs
- src/search/sort/mod.rs
- src/search/sort/sort_.rs
Allow sorting by geo distance.
There's a duplication in unit types right now, I'll need to make refactoring to units to get rid of that.
> Implement geo distance sort

- src/search/queries/compound/bool_query.rs
- src/search/queries/compound/dis_max_query.rs
- src/search/queries/mod.rs
- src/search/queries/params/geo_query.rs
- src/util/should_skip.rs
This streamlines query collection code with rescores, sortings.
> Refactor query collection

- src/search/queries/mod.rs
- src/search/queries/query_collection.rs
Moving to a dedicated file to manage complexity.
> Move query collection to a separate file

- src/search/queries/params/fuzziness.rs
This won't require copying data over.
> Tweak fuzziness serialization

- src/search/mod.rs
- src/search/queries/params/fuzziness.rs
- src/search/suggesters/completion_suggester.rs
- src/search/suggesters/mod.rs
- src/search/suggesters/suggest_context_query.rs
- src/search/suggesters/suggest_fuzziness.rs
- src/search/suggesters/suggester.rs
implements completion suggester serialization and building logic.
> Implement completion suggester

- src/search/request.rs
- src/search/suggesters/suggester.rs
Add suggesters to search requests.
> Add suggester to search request

- src/search/response/mod.rs
- src/search/response/search_response.rs
- src/search/response/suggest.rs
- src/search/response/suggest_option.rs
Adds suggester response to search response.
> Add suggest response

- Cargo.toml
- src/search/rescoring/rescore_collection.rs
ShouldSkip clause was missing.
> Fix rescore skipping

- .github/workflows/CI.yml
Add a CI step to calculate test coverage.
> Generate test coverage

- Cargo.toml
- src/search/request.rs
Allows filtering stored/docvalue fields.
> Add support for stored_fields, docvalue_fields

- Cargo.toml
- src/search/aggregations/pipeline/mod.rs
- src/search/queries/params/inner_hits.rs
- src/search/queries/span/mod.rs
Inner hits can also have docvalue fields - let's add them.
> Add docvalue_fields to inner hits

- src/search/response/source.rs
These should be helpful when creating sources from custom data.
> Allow creating source from value, raw value

- Cargo.toml
- src/search/queries/mod.rs
- src/search/queries/span/mod.rs
- src/search/queries/span/span_containing_query.rs
- src/search/queries/span/span_field_masking_query.rs
- src/search/queries/span/span_first_query.rs
- src/search/queries/span/span_multi_query.rs
- src/search/queries/span/span_near_query.rs
- src/search/queries/span/span_not_query.rs
- src/search/queries/span/span_or_query.rs
- src/search/queries/span/span_term_query.rs
- src/search/queries/span/span_within_query.rs
In favor of https://github.com/vinted/elasticsearch-dsl-rs/pull/141
Closes https://github.com/vinted/elasticsearch-dsl-rs/issues/100
> Implement span queries

- src/lib.rs
- src/search/highlight/highlighter.rs
- src/search/highlight/mod.rs
- src/search/queries/compound/boosting_query.rs
- src/search/queries/compound/constant_score_query.rs
- src/search/queries/full_text/match_phrase_prefix_query.rs
- src/search/queries/full_text/match_phrase_query.rs
- src/search/queries/full_text/match_query.rs
- src/search/queries/joining/nested_query.rs
- src/search/queries/params/negative_boost.rs
- src/search/queries/specialized/distance_feature_query.rs
- src/search/queries/term_level/regexp_query.rs
- src/search/queries/term_level/terms_query.rs
- src/types.rs
These belong to this project only for convenience and should not be exposed to public.
> Make map/set type aliases internal

- src/search/params/coordinate.rs
- src/search/params/units.rs
- src/search/queries/params/fuzziness.rs
- src/search/queries/params/rewrite.rs
Version 1.67.0 introduced a clippy rule requiring to inline printing variables.
> Fix clippy rules

- src/search/queries/compound/function_score_query.rs
- src/search/queries/params/function_score_query.rs
Addresses issues raised in https://github.com/vinted/elasticsearch-dsl-rs/issues/214.
- Makes function score query optional
- Allow providing `filter`, and `weight` to functions
> Fix function score query

- src/search/mod.rs
- src/search/request.rs
- src/search/script_fields/mod.rs
Implements script fields, closes https://github.com/vinted/elasticsearch-dsl-rs/issues/217.
> Implement script fields

- Cargo.toml
Releases:
- https://github.com/vinted/elasticsearch-dsl-rs/pull/229
- https://github.com/vinted/elasticsearch-dsl-rs/pull/230
> Release 0.4.17

- .github/workflows/CI.yml
This is not something I keep track off and it started failing builds.
> Remove codecov

- src/search/aggregations/bucket/date_histogram_aggregation.rs
- src/search/aggregations/bucket/mod.rs
- src/search/aggregations/mod.rs
Closes https://github.com/vinted/elasticsearch-dsl-rs/issues/238.
> Implement date histogram

- Cargo.toml
Releases https://github.com/vinted/elasticsearch-dsl-rs/pull/250
> Release 0.4.19

- src/search/params/number.rs
- src/search/queries/params/function_score_query.rs
- src/search/queries/specialized/distance_feature_query.rs
Deduplicate script from function score and script object, this is some kind of leftover that I forgot and it has finally bit me back.
> Deduplicate script objects

- src/lib.rs
- `private_in_public` has been removed
- `clippy::needless_doctest_main` fixed
> Fix breaking 1.74.0 linting changes

- src/search/collapse/mod.rs
- src/search/mod.rs
- src/search/queries/params/inner_hits.rs
- src/search/request.rs
Implements from inactive https://github.com/vinted/elasticsearch-dsl-rs/pull/254 collapse correctly
> feat: add collapse

- .github/workflows/CI.yml
- src/search/params/term.rs
- src/search/sort/sort_special_field.rs
CI actions not triggered when code's pushed to pull request. Let's try fixing that
> fix: update ci actions triggers

- src/search/params/text.rs
- src/search/rescoring/rescore_.rs
CI builds fail due to clippy complaints, let's address them.
> chore: fix clippy errors
